### ISSUE TITLE
[Bug]: Contact binary sensor reports inverted value

### ISSUE THREAD

**Issue by Ultra-bob** [t0bst4r/matterbridge-home-assistant#144]
### What happened?

My door sensors are reporting open when they are closed and closed when they are opened. This is because they are reporting as contact sensors, which detect contact (`true`) when the door is closed, but in home assistant, an open door is `true` so they are inverted.

### Your configuration

```yml
HOME_ASSISTANT_CLIENT_CONFIG: |
  {
    "includePatterns": ["binary_sensor.*_door"]
  }
```

### Version

1.5.2
