### ISSUE TITLE
covers are appeared inverted 

### ISSUE THREAD

**Issue by tammeryousef1006** [t0bst4r/matterbridge-home-assistant#234]
### What happened?

my cover already fully opened and appears fully close at matter , if i set position to 80% then at matter appears opened to 20% , its working opposite way 

### Your configuration

official ha add on

### Relevant log output

```shell
no log needed
```

### Version

latest

**Comment by tammeryousef1006** [comment]
Open close stop working correctly,  but full open in real shows closed , and full closed in real shows opened , also position are working opposite way , going to pos 80 makes cover goes to 20 ,  going to pos 10 makes cover to go to 90 , i hope i could explain it well

**Comment by t0bst4r** [comment]
Yes, I understood that. Would be nice to know if that’s a bug for all or specific for your device.

I’m not be at home for three days. I’ll take care on the weekend

**Comment by tammeryousef1006** [comment]
Im outside also can't check rest of covers , will see once im home

**Comment by baeksj** [comment]
Here, both of my blinds are also displayed in an inverted state.

**Comment by genehand** [comment]
I have the.. opposite problem. :) My positions are reported correctly but asking alexa to open the blinds will close them.

Zemismart ZM25RZ01-30 rollershade through zigbee2mqtt, motor direction in normal mode (vs reversed).

**Comment by tammeryousef1006** [comment]
its the same problem not different , try for example to open to position 20 and look what happen in real , for me I use shelly cover and its easier to track this

**Comment by genehand** [comment]
Yes, same problem in reverse.

"Alexa, set the office blinds to 20 percent" -> blinds go to 20%.  

"Alexa, open the blinds" -> blinds close (0%)

**Comment by t0bst4r** [comment]
Could you test in the mean time what happens when setting the position to 20 via home assistant. Currently I just forward the percentage from matter to HA without any change. So I assume 20% (open) for Alexa means 80% in HA ?

**Comment by tammeryousef1006** [comment]
for me i test with ha and smartthings and both works same way as offical shelly app , 0 is closed and 100 is open

**Comment by tammeryousef1006** [comment]
any percent between 0 - 100 is mean partially opened

**Comment by tammeryousef1006** [comment]
the issue with @genehand is abit different , he claims that he can sit the desired position correctly , but for me its sit opposite percent to 100% , if i go 10% the cover goes 90% , if i set 20% the cover goes 80% , and for sure the only correct percent is 50% lol

**Comment by genehand** [comment]
> If Alexa seems to assume that 0% is „open“. Then 20% should mean „from the top“ and not „from the bottom“.

The percentages with covers seemed weird to me at first, I think it's based on the amount of light let through.  So 0% is closed, 20% is from the bottom, and 100% is fully open.  

> what are you experiencing **exactly**, if it’s not the same as for the others?

The position attribute is working correctly for me and showing the same value in zigbee2mqtt, home assistant, and the alexa app. "Set the blinds to 20%" works as expected with the blinds open 20% from the bottom, still covering 80% of the window.  "Set the blinds to 100%" works correctly and opens the blinds.  The only weird part is that using "Open the blinds" closes them, setting them to 0%.  This was working correctly before with matterbridge-zigbee2mqtt, I'd just like to consolidate plugins and have everything go through Home Assistant.  

@tammeryousef1006 I was wondering if maybe you have the `invert_directions` setting enabled with shelly and that could be giving us opposite results.  But then I realized I have 2 of the same motor, 1 normal motor direction and the other reversed.  And I'm getting the same behavior from both so 🤷‍♂️ 😄

**Comment by tammeryousef1006** [comment]
thats really confusing , i think matter should follow the entity of ha despite of any other settings , for me the basic commands like (open , close , stop) works perfectly but inverted closed opened , and going to position obvious for me going opposite percentage  , i think i should integrate the rest covers and see if all behave the same

**Comment by t0bst4r** [comment]
Matter.js specification: 
Open: 0%
Closed: 100%

Home Assistant ([HA Position Template](https://www.home-assistant.io/integrations/cover.template/#position_template)):
Closed: 0
Open: 100

**I will definetly reverse it.**

In the mean time I got a mocked cover entity working with a input_number and a template-cover entity.
Anyway Alexas Translations seem to be wrong for covers. It says (Translated from German Alexa app) "Degree of opening". But when I say "close the cover" it puts it to 100% (matter => closed). So thats wrong, but it should then be the "degree of closing" instead.

Is that the problem you are facing @genehand ?
To be honest: i think its a bug of alexa or at least a mistake in the label of the property in Alexa.

**Comment by t0bst4r** [comment]
Just merged it to main, and triggered the release. Should be fixed with `2.3.2`.
If you do not agree feel free to reopen this issue.

**Comment by tammeryousef1006** [comment]
for me latest fixed 2.3.2 worked for me thanks

**Comment by genehand** [comment]
Hmm yeah now I'm in the inverted scenario where open/close commands work but the percentages go the other way.  Makes sense since home assistant and matter don't line up there.  I'll try using a template cover entity to flip it.

My alexa app also says "Opening". I'd guess that's based on the same "100% = open" logic that doesn't match the matter spec now.  Thanks for getting this going!

**Comment by genehand** [comment]
Ok that mostly works, in case anyone's interested: 

```yaml
cover:
  - platform: template
    covers:
      office_blinds_matter:
        device_class: shade
        friendly_name: Office blinds
        unique_id: office_blinds_matter
        availability_template: "{{ has_value('cover.office_blinds') }}"
        value_template: "{{ states('cover.office_blinds') }}"
        position_template: "{{ 100 - state_attr('cover.office_blinds', 'current_position') }}"
        stop_cover:
          service: cover.stop_cover
          target:
            entity_id: cover.office_blinds
        set_cover_position:
          service: cover.set_cover_position
          target:
            entity_id: cover.office_blinds
          data:
            position: >
              {% if position == 100 or position == 0 %}
                {{ position }}
              {% else %}
                {{ 100 - position }}
              {% endif %}
```

The one weird workaround is flipping the full open/close positions between 0 and 100.  This makes it possible for "open the blinds" to work, but now "set the blinds to 99%" will open them almost all the way while "set the blinds to 100%" will close them.  I'd never use the 100% command so it works for me 😄
