### ISSUE TITLE
Failed to start plugin matterbridge-home-assistant: Error: Home Assistant Access Token is not set.

### ISSUE THREAD

**Issue by Cheerpipe** [t0bst4r/matterbridge-home-assistant#67]
Hi. i am trying to use latest docker (0.50) with config_file env but i get this error on container start:

Failed to start plugin matterbridge-home-assistant: Error: Home Assistant Access Token is not set.

![image](https://github.com/t0bst4r/matterbridge-home-assistant/assets/972765/13e1da30-44d4-43b8-b522-7fa20fe9e238)

My docker compose:

```
services:
  matterbridge-home-assistant:
    container_name: matterbridge-home-assistant
    image: ghcr.io/t0bst4r/matterbridge-home-assistant:latest
    restart: unless-stopped
    network_mode: host
    environment:
      CONFIG_FILE: /config/matterbridge-config.json
    volumes:
      - /config/matterbridge-home-assistant/data:/root/.matterbridge
      - /config/matterbridge-home-assistant/config:/config:ro
```

Content of` matterbridge-config.json` located in` /config/matterbridge-home-assistant/config`

```
{
  "homeAssistantUrl": "http://192.168.1.53:8123",
  "homeAssistantAccessToken": "eyJh....................5g",
  "homeAssistantClientConfig": {
    "includeDomains": ["scenes"]
  }
}
```

I have also checked the config file inside container and it is passed OK:

![image](https://github.com/t0bst4r/matterbridge-home-assistant/assets/972765/2a689a06-1187-4d61-9ecc-c733de4bca12)
