### ISSUE TITLE
Bug: Can´t install/update the home assistant plugin from within Matterbridge

### ISSUE THREAD

**Issue by Jibbonator** [t0bst4r/matterbridge-home-assistant#97]
At First I Would like to thank t0bst4r for his outstanding Plugin.
I´ve waited a long time for something like this, because I´m no programmer myself xD
I really like the Idea to connect my homeassistant local to Alexa without the need of an custom Alexa skill and own Domain.
I know i could use Emulated Hue, but it doesn´t support other Entity Types than Lights.

**Here´s my Problem:**

I have a Standalone Docker environment with working Matterbridge with Zigbee2Mqtt Addon.
I like it because my Mqtt Broker is standalone and could even work without Homeassistant running.
I use it because in the momentary state it supports many entity Types.
[https://github.com/Luligu/matterbridge-zigbee2mqtt](url)

I´m using the official matterbridge Docker Container.

I try to add "matterbridge-home-assistant"

The Addon is installed but doesn´t start. Here is a screenshot and my config:

![image](https://github.com/t0bst4r/matterbridge-home-assistant/assets/42499662/bba1026f-6313-4f9b-8915-b64071507e60)

here´s my config:

```yaml
services:
  matterbridge:
    container_name: matterbridge
    image: luligu/matterbridge:latest # Matterbridge image with the latest tag
    network_mode: host # Ensures the Matter mdns works
    restart: unless-stopped # Ensures the container always restarts automatically
    volumes:
      - "/mnt/Matterbridge:/root/Matterbridge" # Mounts the Matterbridge plugin directory
      - "/mnt/Matterbridge/.matterbridge:/root/.matterbridge" # Mounts the Matterbridge storage directory
    environment:
      HOME_ASSISTANT_URL: 'http://192.*.*.*:8123'
      HOME_ASSISTANT_ACCESS_TOKEN: 'eyJ**********4k'
      HOME_ASSISTANT_CLIENT_CONFIG: |
        {
          "includeDomains": ["light", "media_player"],
          "excludePatterns": ["media_player.*echo*"]
        }
          "excludePatterns": ["media_player.*echo*"]
        }
```
An I´m overlooking something?
Is my config correct?
I tried to look into the Logs but "matterbridge-home-assistant" ist even in it.

Any help is appreciated

update:
Just updated to 1.1.3.
No it´s starting but with no devices.

the error in the log is:

> [12:21:51.231] [HomeAssistantMatterAdapter] Failed to register device for light.wzd1 
[12:21:51.231] [HomeAssistantMatterAdapter] Error: Only supported EndpointInterface implementation is Endpoint 
[12:21:51.233] [HomeAssistantMatterAdapter] Failed to register device for light.wzd2 
[12:21:51.233] [HomeAssistantMatterAdapter] Error: Only supported EndpointInterface implementation is Endpoint 
[12:21:51.234] [HomeAssistantMatterAdapter] Failed to register device for light.wzd3 
[12:21:51.234] [HomeAssistantMatterAdapter] Error: Only supported EndpointInterface implementation is Endpoint 
[12:21:51.236] [HomeAssistantMatterAdapter] Failed to register device for light.wzd4 
[12:21:51.236] [HomeAssistantMatterAdapter] Error: Only supported EndpointInterface implementation is Endpoint 
[12:21:51.237] [HomeAssistantMatterAdapter] Failed to register device for light.shellywohnzimmerlicht 
[12:21:51.237] [HomeAssistantMatterAdapter] Error: Only supported EndpointInterface implementation is Endpoint 
[12:21:51.238] [HomeAssistantMatterAdapter] Failed to register device for light.0xa4c1381250d6ac83 
[12:21:51.239] [HomeAssistantMatterAdapter] Error: Only supported EndpointInterface implementation is Endpoint 
[12:21:51.241] [HomeAssistantMatterAdapter] Failed to register device for media_player.shield_2 
[12:21:51.241] [HomeAssistantMatterAdapter] Error: Only supported EndpointInterface implementation is Endpoint 
[12:21:51.242] [HomeAssistantMatterAdapter] Failed to register device for media_player.shield 
[12:21:51.242] [HomeAssistantMatterAdapter] Error: Only supported EndpointInterface implementation is Endpoint 
[12:21:51.244] [HomeAssistantMatterAdapter] Failed to register device for light.flur_kamera_floodlight_timed 

![image](https://github.com/t0bst4r/matterbridge-home-assistant/assets/42499662/a0ead94f-f6a7-4640-87c7-df0c08e1c9d3)

There is a workaround for the standalone installation:
https://github.com/t0bst4r/matterbridge-home-assistant/issues/59

But I don´t know to adapt this to my problem.
